language: python

notifications:
  email:
    on_success: never
    on_failure: always

python:
  - 2.7
  - 3.5
  - 3.6

matrix:

  include:
    # # Ubuntu 14.04
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   python: "2.7"
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   python: "3.5"
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   python: "3.6"

    # MacOS 10.11
    - os: osx
      osx_image: xcode8
      python: "2.7"

    # MacOS 10.12
    - os: osx
      osx_image: xcode9.2
      python: "2.7"

    # MacOS 10.13
    - os: osx
      osx_image: xcode9.4
      python: "2.7"

# before_install stops immediately at non-zero exit code
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh;
    fi
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda;
  - export PATH="$HOME/miniconda/bin:$PATH";
  - conda --version

script:
  - which conda
  - conda info
  - which python
  - python -V
  - python -c "import platform; print(platform.architecture())"
