language: ruby

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    # MacOS 10.13
    - os: osx
      osx_image: xcode9.4
      env: TOXENV=py36

install:
    - ./install_python.sh

script:
  - which python
  - python -V
  - python -c "import platform; print(platform.architecture())"

  - which pyenv
  - pyenv global 3.6.5
  - which python
  - python -V
  - which python3
  - python3 -V
