language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      env: PYTHON_VERSION=3.5

    - os: linux
      dist: bionic
      sudo: true
      env: PYTHON_VERSION=3.6

    - os: linux
      dist: bionic
      sudo: true
      env: PYTHON_VERSION=3.7

    - os: linux
      dist: bionic
      sudo: true
      env: PYTHON_VERSION=3.8

    - os: osx
      osx_image: xcode11.4
      env: PYTHON_VERSION=3.5

    - os: osx
      osx_image: xcode11.4
      env: PYTHON_VERSION=3.6

    - os: osx
      osx_image: xcode11.4
      env: PYTHON_VERSION=3.7

    - os: osx
      osx_image: xcode11.4
      env: PYTHON_VERSION=3.8

install:
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

script:
  # Conda install
  - conda create -y -q -n env_conda python=${PYTHON_VERSION}
  - conda activate env_conda
  - conda install --debug -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - conda deactivate

  # Pip install
  - conda create -y -q -n env_pip python=${PYTHON_VERSION}
  - conda activate env_pip
  - pip install -U open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - conda deactivate
