language: python

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
    # MacOS 10.13
    - os: osx
      osx_image: xcode9.4
      env: TOXENV=py36

install:
    - ./install_python_osx.sh

script:
  - which python
  - python -V
  - python -c "import platform; print(platform.architecture())"
