version: '1.0.{build}'

platform:
  - x86
  - x64

before_build:
- ps: |
    if ($env:PLATFORM -eq "x64") {
      $env:PATH = "C:\Miniconda36-x64\Scripts;$env:PATH"
    }

build_script:
  - where conda
  - conda info
  - where python
  - python -V
  - python -c "import platform; print(platform.architecture())"

  # Native Conda
  - conda create -y -q -n env3.5_conda python=3.5
  - activate env3.5_conda
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.6_conda python=3.6
  - activate env3.6_conda
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.7_conda python=3.7
  - activate env3.7_conda
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.8_conda python=3.8
  - activate env3.8_conda
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  # Pip in Conda
  - conda create -y -q -n env3.5_conda_pip python=3.5
  - activate env3.5_conda_pip
  - pip install -U open3d-python
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.6_conda_pip python=3.6
  - activate env3.6_conda_pip
  - pip install -U open3d-python
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.7_conda_pip python=3.7
  - activate env3.7_conda_pip
  - pip install -U open3d-python
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.8_conda_pip python=3.8
  - activate env3.8_conda_pip
  - pip install -U open3d-python
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate
