version: '1.0.{build}'

platform:
  - x86
  - x64

before_build:
- ps: |
    if ($env:PLATFORM -eq "x86") {
      $env:PATH = "C:\Miniconda36\Scripts;$env:PATH"
      $env:CONDA_FORCE_32BIT = "1"
    }
    if ($env:PLATFORM -eq "x64") {
      $env:PATH = "C:\Miniconda36-x64\Scripts;$env:PATH"
    }

build_script:
  - where conda
  - conda info
  - where python
  - python -V
  - python -c "import platform; print(platform.architecture())"

  - conda create -y -q -n env2.7 python=2.7
  - activate env2.7
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.5 python=3.5
  - activate env3.5
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate

  - conda create -y -q -n env3.6 python=3.6
  - activate env3.6
  - conda install -y -q -c open3d-admin open3d
  - python -c "from open3d import *; import open3d; print(open3d)"
  - deactivate
